export const products = [
  {
    id: 1,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?sapato',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 2,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?sapatos',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 3,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?sandalia',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 4,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?chinelo',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 5,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?calcado',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 6,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?sapato',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 7,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?tênis',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 8,
    name: 'Basic Tee',
    href: `/product/item`,
    imageSrc: 'https://source.unsplash.com/random/600x400/?calcado+esportivo',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  }
]